name: Update README from Markdown API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch Markdown content
        id: fetch_markdown
        run: |
          curl -s https://www.fbritoferreira.com/cv/markdown -o README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if README.md is new or has changes
          if git status --porcelain README.md | grep .; then
            git add README.md
            git commit -m "Update README.md from Markdown API"
            git push origin main
          else
            echo "No changes in README.md"
          fi
